CREATE DATABASE EVALUACION_LUIS_STEVE_DIAZ_FUENTES;	
USE EVALUACION_LUIS_STEVE_DIAZ_FUENTES;

CREATE TABLE ESTADO_USUARIO (ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 TITULO NVARCHAR(50) NOT NULL,
 CLAVE NVARCHAR(50) NOT NULL UNIQUE
 );
 
INSERT IGNORE INTO ESTADO_USUARIO (TITULO, CLAVE) VALUES ('Activo','activo'),
 ('Baja Permanente', 'baja');
 
select * from ESTADO_USUARIO;
 
 CREATE TABLE USUARIO (ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 NOMBRE NVARCHAR(100) NOT NULL,
 FECHA DATE NOT NULL,
 TELEFONO INT NOT NULL,
 CORREO NVARCHAR(250) NOT NULL UNIQUE,
 CREACION DATETIME DEFAULT NOW(),
 ESTADO_USUARIO_ID INT NOT NULL,
 FOREIGN KEY (ESTADO_USUARIO_ID) REFERENCES ESTADO_USUARIO (ID)
 );
 
select * from USUARIO;

SELECT ID, NOMBRE, TELEFONO, CORREO 
        FROM USUARIO
        ORDER BY ID ASC;
        
        SELECT EU.TITULO AS estado, COUNT(U.ID) AS conteo
        FROM ESTADO_USUARIO EU
        JOIN USUARIO U ON EU.ID = U.ESTADO_USUARIO_ID
        GROUP BY EU.TITULO
        ORDER BY conteo DESC;
        
SELECT 
    u.ID, 
    u.NOMBRE, 
    u.TELEFONO, 
    u.CORREO, 
    eu.TITULO AS ESTADO 
FROM 
    USUARIO u 
JOIN 
    ESTADO_USUARIO eu ON u.ESTADO_USUARIO_ID = eu.ID 
WHERE 
    DATE(u.CREACION) = '2025-10-24' 
ORDER BY 
    u.CREACION DESC;
    
    
SELECT u.ID, u.NOMBRE, u.TELEFONO, u.CORREO, eu.titulo AS ESTADO 
FROM USUARIO u
JOIN ESTADO_USUARIO eu ON u.ESTADO_USUARIO_ID = eu.id
ORDER BY u.NOMBRE ASC

        